name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    types:
      - closed


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses:  actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build the Docker image
        working-directory: .
        run: docker build . --file Dockerfile --tag docker.io/tanchwa/blue-green-app-test:${{ github.sha }}

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 #v0.35.0 using Trivy v0.69.3
        with:
          image-ref: 'docker.io/tanchwa/blue-green-app-test:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          output: trivy-report.txt
        continue-on-error: true

      - name: Publish Scan as Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: trivy-scan
          path: trivy-report.txt

      - name: Push the Docker image
        run: docker login -u tanchwa -p ${{ secrets.DOCKER_TOKEN }} && docker push docker.io/tanchwa/blue-green-app-test:${{ github.sha }}
